# Generated by Django 3.2.9 on 2023-07-19 20:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo_app', '0002_alter_todoitems_assigned_to'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TodoItems',
            new_name='TodoItem',
        ),
    ]
